#!/usr/bin/env php
<?php

set_time_limit(10);
set_include_path(get_include_path().PATH_SEPARATOR.__DIR__.'/vendor/pear-pear/Math_Vector'.PATH_SEPARATOR.__DIR__.'/vendor/pear-pear/Math_Matrix');

$loader = require(__DIR__.'/vendor/autoload.php');

use Symfony\Component\Console\Application;
use LatticeEncoding\Command\EncodeCommand;
use LatticeEncoding\Command\DecodeCommand;

function dump($array) {
    foreach ($array as $row) {
        foreach ($row as $value) {
            echo $value;
        }
        echo PHP_EOL;
    }
}

$application = new Application();
$application->add(new EncodeCommand());
$application->add(new DecodeCommand());
$application->run();
